### ISSUE TITLE
Missing config.json

### ISSUE THREAD

**Issue by Vilicus** [dpalay/RaiderBot#2]
Sorry if I'm being dumb.  Never tried to run anything like this before.   Was told by "Gladiator10864" I could use this on my server.  

Anyway, I tried running this locally after installing node.js on my system.   The program errored because it couldn't find config.json file.  Is that something I need to create myself?   Would it need to include anything within the file?

Also tried running this locally through Heroku but I am assuming it errored out because of the above issue as well.   

Some kind of config.json.example would be super helpful that I could then modify to include my own information.

**Comment by dpalay** [comment]
Hi Vilicus,
Gladiator is a little ambitious if he's suggesting this to other people already.  The bot is still in a pretty early phase and is still rapidly shifting.  It was designed specifically for our discord server, so it will take quite a bit of tweaking to get it to run well anywhere else.
There are several values that you will need to store in the config.json file, since I'm not posting my bot's key onto Github :)
I'm at work, so don't have access to my actual files, but I can probably help you out this weekend.

**Comment by Vilicus** [comment]
Yeah totally understand hiding the bots key.  Our servers bot was shut down
without notice last night leaving 7200+ users high and dry.  Im now
frantically looking for a replacement.  I think if all im missing is the
config file, if you could copy yours and replace the sensitive stuff with
"your info here" I could get it figured out.  Unless there's more than that
missing of course.

Anyway, been looking at yours closely over the last few weeks, Im quite
impressed.

**Comment by dpalay** [comment]
Do you have an invite to your discord server?  I can stop in and give you a hand there.

**Comment by Vilicus** [comment]
https://discord.gg/eUrrx8y

**Comment by dpalay** [comment]
Update:  
Added content at the beginning of the Raider.js file to display what the config.json format should look like.  Also going to be working on the readme file... soon-ish.

We did get the bot running on Vilicus's server.
